// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYyuRnuL5kXQ_KDKlTp0btk_FGYyk8WIs',
    appId: '1:250741619233:web:36e423195428b37306c160',
    messagingSenderId: '250741619233',
    projectId: 'shatter-4a5d2',
    authDomain: 'shatter-4a5d2.firebaseapp.com',
    storageBucket: 'shatter-4a5d2.firebasestorage.app',
    measurementId: 'G-N31MVN4EE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoOHlzWCCLlvpeSfzn3CuU1JOqrgchFIY',
    appId: '1:250741619233:android:e05ee1ae15b8917906c160',
    messagingSenderId: '250741619233',
    projectId: 'shatter-4a5d2',
    storageBucket: 'shatter-4a5d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTB0HuoZPqWBLuyaH8x7GfbLHfaIrV4NU',
    appId: '1:250741619233:ios:17ff30b54a2cf6c006c160',
    messagingSenderId: '250741619233',
    projectId: 'shatter-4a5d2',
    storageBucket: 'shatter-4a5d2.firebasestorage.app',
    iosBundleId: 'com.example.shatterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTB0HuoZPqWBLuyaH8x7GfbLHfaIrV4NU',
    appId: '1:250741619233:ios:17ff30b54a2cf6c006c160',
    messagingSenderId: '250741619233',
    projectId: 'shatter-4a5d2',
    storageBucket: 'shatter-4a5d2.firebasestorage.app',
    iosBundleId: 'com.example.shatterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYyuRnuL5kXQ_KDKlTp0btk_FGYyk8WIs',
    appId: '1:250741619233:web:147294f0cc8db2fb06c160',
    messagingSenderId: '250741619233',
    projectId: 'shatter-4a5d2',
    authDomain: 'shatter-4a5d2.firebaseapp.com',
    storageBucket: 'shatter-4a5d2.firebasestorage.app',
    measurementId: 'G-FTVE8VWM21',
  );
}
